// counter-angular/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  title = "counter-angular";
  count = 0

  increment() {
    this.count++;
  }

  decrement() {
    this.count--;
  }
}

<div class="App">
  <div>
    <a href="https://angular.io" target="_blank">
      <img
        src="/assets/angular.svg"
        style="width: 100px"
        class="logo"
        alt="Vite logo"
      />
    </a>
  </div>
  <h1>Angular</h1>
  <div>{{ count }}</div>
  <div class="card">
    <button (click)="increment()">+</button>
    <button (click)="decrement()">-</button>
  </div>
</div>

// counter-react/src/App.tsx
import { useState } from "react";
import reactLogo from "./assets/react.svg";
import "./App.css";

export default function App() {
  const [count, setCount] = useState(0);

  function increment() {
    setCount((prev) => ++prev);
  }

  function decrement() {
    setCount((prev) => --prev);
  }

  return (
    <div className="App">
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src="/vite.svg" className="logo" alt="Vite logo" />
        </a>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div>{count}</div>
      <div className="card">
        <button onClick={increment}> + </button>
        <button onClick={decrement}> - </button>
      </div>
    </div>
  );
}
